export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FLASH_MESSAGE = "FLASH_MESSAGE";
export const CLEAR_CURRENT_FLASH_MESSAGE = "CLEAR_CURRENT_FLASH_MESSAGE";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const GET_SESSION_CART = "GET_SESSION_CART";
export const SESSION_CART_LOADING = "SESSION_CART_LOADING";
export const CLEAR_CURRENT_SESSION_CART = "CLEAR_CURRENT_SESSION_CART";
export const GET_SESSION_CART_BY_ID = "GET_SESSION_CART_BY_ID";
export const PRODUCT_ADDED_IN_SESSION_CART_BY_ID =
  "PRODUCT_ADDED_IN_SESSION_CART_BY_ID";
export const PRODUCT_IN_SESSION_CART_INC_BY_1_ID =
  "PRODUCT_IN_SESSION_CART_INC_BY_1_ID";
export const PRODUCT_IN_SESSION_CART_DEC_BY_1_ID =
  "PRODUCT_IN_SESSION_CART_DEC_BY_1_ID";
export const PRODUCT_IN_SESSION_CART_DELETE_BY_ID =
  "PRODUCT_IN_SESSION_CART_DELETE_BY_ID";

export const GET_WAREHOUSE = "GET_WAREHOUSE";
export const WAREHOUSE_LOADING = "WAREHOUSE_LOADING";
export const GET_WAREHOUSE_BY_ID = "GET_WAREHOUSE_BY_ID";

export const GET_STOCK = "GET_STOCK";
export const STOCK_LOADING = "STOCK_LOADING";
export const CLEAR_CURRENT_STOCK = "CLEAR_CURRENT_STOCK";
export const GET_STOCK_BY_ID = "GET_STOCK_BY_ID";
export const STOCK_EDITED_BY_ID = "STOCK_EDITED_BY_ID";
export const ADD_ON_EXISTING_PRODUCT_STOCK = "ADD_ON_EXISTING_PRODUCT_STOCK";
export const REMOVE_ON_EXISTING_PRODUCT_STOCK =
  "REMOVE_ON_EXISTING_PRODUCT_STOCK";

export const GET_SINGLE_PRODUCT_ALL_ITEM_WITH_TOTALQTY_WAREHOUSE_BY_ID =
  "GET_SINGLE_PRODUCT_ALL_ITEM_WITH_TOTALQTY_WAREHOUSE_BY_ID";

export const GET_ORIGIN_WAREHOUSE_PROD_STOCKS =
  "GET_ORIGIN_WAREHOUSE_PROD_STOCKS";

export const GET_ORIGIN_WAREHOUSE_PROD_STOCKS_LOADING =
  "GET_ORIGIN_WAREHOUSE_PROD_STOCKS_LOADING";

export const GET_SESSION_WAREHOUSE_TRANSFER = "GET_SESSION_WAREHOUSE_TRANSFER";

export const GET_ALL_WAREHOUSE_TRANSFER_HISTORY =
  "GET_ALL_WAREHOUSE_TRANSFER_HISTORY";

export const SESSION_WAREHOUSE_TRANSFER_LOADING =
  "SESSION_WAREHOUSE_TRANSFER_LOADING";

export const WAREHOUSE_TRANSFER_HISTORY_LOADING =
  "WAREHOUSE_TRANSFER_HISTORY_LOADING";

export const GET_WAREHOUSE_TRANSFER_HISTORY_BY_DATE =
  "GET_WAREHOUSE_TRANSFER_HISTORY_BY_DATE";

export const GET_WAREHOUSE_TRANSFER_HISTORY_BY_ID =
  "GET_WAREHOUSE_TRANSFER_HISTORY_BY_ID";
export const CLEAR_CURRENT_WAREHOUSE_TRANSFER =
  "CLEAR_CURRENT_WAREHOUSE_TRANSFER";

export const PRODUCT_ADDED_IN_SESSION_WAREHOUSE_TRANSFER_BY_ID =
  "PRODUCT_ADDED_IN_SESSION_WAREHOUSE_TRANSFER_BY_ID";
export const PRODUCT_DELETE_IN_SESSION_WAREHOUSE_TRANSFER_BY_ID =
  "PRODUCT_DELETE_IN_SESSION_WAREHOUSE_TRANSFER_BY_ID";
export const GET_SESSION_WAREHOUSE_TRANSFER_BY_ID =
  "GET_SESSION_WAREHOUSE_TRANSFER_BY_ID";
export const GET_WAREHOUSE_TRANSFER_PROD_STOCKS_LOADING =
  "GET_WAREHOUSE_TRANSFER_PROD_STOCKS_LOADING";
export const GET_WAREHOUSE_TRANSFER_PROD_STOCKS_LOADING_STOP =
  "GET_WAREHOUSE_TRANSFER_PROD_STOCKS_LOADING_STOP";
export const PRODUCT_IN_SESSION_WAREHOUSE_TRANSFER_INC_BY_ID =
  "PRODUCT_IN_SESSION_WAREHOUSE_TRANSFER_INC_BY_ID";

export const GET_NEW_STOCK_HISTORY_DATES = "GET_NEW_STOCK_HISTORY_DATES";

export const GET_NEW_STOCK_HISTORY_DATES_LOADING =
  "GET_NEW_STOCK_HISTORY_DATES_LOADING";

export const GET_NEW_STOCKS_HISTORY_BY_DATE = "GET_NEW_STOCKS_HISTORY_BY_DATE";

export const GET_EXISTING_STOCK_HISTORY_DATES =
  "GET_EXISTING_STOCK_HISTORY_DATES";

export const GET_EXISTING_STOCK_HISTORY_DATES_LOADING =
  "GET_EXISTING_STOCK_HISTORY_DATES_LOADING";

export const GET_EXISTING_STOCKS_HISTORY_BY_DATE =
  "GET_EXISTING_STOCKS_HISTORY_BY_DATE";

export const GET_ADVANCED_INVENTYORY_SEARCH_RESULT =
  "GET_ADVANCED_INVENTYORY_SEARCH_RESULT";

export const GET_ADVANCED_INVENTYORY_SEARCH_RESULT_LOADING =
  "GET_ADVANCED_INVENTYORY_SEARCH_RESULT_LOADING";
