export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FLASH_MESSAGE = "FLASH_MESSAGE";
export const CLEAR_CURRENT_FLASH_MESSAGE = "CLEAR_CURRENT_FLASH_MESSAGE";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const GET_SESSION_CART = "GET_SESSION_CART";
export const SESSION_CART_LOADING = "SESSION_CART_LOADING";
export const CLEAR_CURRENT_SESSION_CART = "CLEAR_CURRENT_SESSION_CART";
export const GET_SESSION_CART_BY_ID = "GET_SESSION_CART_BY_ID";
export const PRODUCT_ADDED_IN_SESSION_CART_BY_ID =
  "PRODUCT_ADDED_IN_SESSION_CART_BY_ID";
export const PRODUCT_IN_SESSION_CART_INC_BY_1_ID =
  "PRODUCT_IN_SESSION_CART_INC_BY_1_ID";
export const PRODUCT_IN_SESSION_CART_DEC_BY_1_ID =
  "PRODUCT_IN_SESSION_CART_DEC_BY_1_ID";
export const PRODUCT_IN_SESSION_CART_DELETE_BY_ID =
  "PRODUCT_IN_SESSION_CART_DELETE_BY_ID";

export const GET_WAREHOUSE = "GET_WAREHOUSE";
export const WAREHOUSE_LOADING = "WAREHOUSE_LOADING";
export const GET_WAREHOUSE_BY_ID = "GET_WAREHOUSE_BY_ID";

export const GET_STOCK = "GET_STOCK";
export const STOCK_LOADING = "STOCK_LOADING";
export const CLEAR_CURRENT_STOCK = "CLEAR_CURRENT_STOCK";
export const GET_STOCK_BY_ID = "GET_STOCK_BY_ID";
export const STOCK_EDITED_BY_ID = "STOCK_EDITED_BY_ID";
export const ADD_ON_EXISTING_PRODUCT_STOCK = "ADD_ON_EXISTING_PRODUCT_STOCK";
export const REMOVE_ON_EXISTING_PRODUCT_STOCK =
  "REMOVE_ON_EXISTING_PRODUCT_STOCK";
